<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

//Generated By PlantUML Command
class Activity extends Model
{
    protected $fillable = [
        'day',
        'time',
        'duration',
        'description',
    ];

    public function animals()
    {
        return $this->hasMany(Animal::class,'activity_id');
    }
}
