<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

//Generated By PlantUML Command
class Animal extends Model
{
    protected $fillable = [
        'name',
        'species_id',
        'enclosure_id',
        'activity_id',
        'date_of_birth',
        'gender',
        'weight',
        'health_status',
    ];

    public function species()
    {
        return $this->belongsTo(Species::class, 'species_id');
    }

    public function enclosure()
    {
        return $this->belongsTo(Enclosure::class, 'enclosure_id');
    }

    public function caretaker_animals()
    {
        return $this->hasMany(Caretaker_Animal::class, 'animal_id');
    }

    public function activity()
    {
        return $this->belongsTo(Activity::class, 'activity_id');
    }
}
