<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

//Generated By PlantUML Command
class Animal extends Model
{
    protected $fillable = [
        'name',
        'species_id',
        'enclosure_id',
        'activity_id',
        'date_of_birth',
        'gender',
        'weight',
        'health_status',
    ];

    public function species()
    {
        return $this->belongsTo('App\Models\Species');
    }

    public function enclosure()
    {
        return $this->belongsTo('App\Models\Enclosure');
    }

    public function caretaker_animals()
    {
        return $this->hasMany('App\Models\Caretaker_Animal');
    }

    public function activity()
    {
        return $this->belongsTo('App\Models\Activity');
    }
}
