<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

//Generated By PlantUML Command
class Enclosure extends Model
{
    protected $fillable = [
        'capacity',
        'location',
        'type',
    ];

    public function animals()
    {
        return $this->hasMany(Animal::class ,'enclosure_id');
    }
}
